---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: cloudflare-ddns-
labels:
  - pairs:
      app.kubernetes.io/name: cloudflare-ddns
    includeSelectors: true
resources:
  - ./config.secret.sops.yaml
  - ./deployment.yaml
