---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: mltb
    includeSelectors: true
resources:
  - ./base.httproute.yaml
  - ./deployment.yaml
  - ./env.configmap.yaml
  - ./env.secret.sops.yaml
  - ./rlcone.httproute.yaml
  - ./sa-accounts.secret.sops.yaml
  - ./sa-token.secret.sops.yaml
  - ./service.yaml
images:
  - name: ghcr.io/kevinnitrog/homelab/mltb
    digest: sha256:d4cce6dd3a9e8b38cc5b4c21fe43e01b77b219a907ebb8ee0096584be2e30d88
