# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cnpg-grafana-auth
stringData:
  username: ${GRAFANA_DB_USER}
  password: ${GRAFANA_DB_PASSWORD}
