---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-cnpg-grafana
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 18
  storage:
    size: 500Mi
  monitoring:
    enablePodMonitor: false
  postgresql:
    parameters:
      timezone: ${TIMEZONE}
      log_timezone: ${TIMEZONE}
  bootstrap:
    initdb:
      database: grafana
      secret:
        name: grafana-cnpg-grafana-auth
  managed:
    services:
      disabledDefaultServices:
        - r
        - ro
