# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: r2-credentials
stringData:
  accessKeyId: ENC[AES256_GCM,data:6ekKFkGjtOQcy4OCyA+ZBivyXJHWKRZ7NTsw8LBzXNA=,iv:6pxvvcS4DtQnJtHhmWmmgRg7XfajeDxLDKRqaZiaHkQ=,tag:Weg8nuJSJHsqUhPMTxk+xw==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:uhYarg3tZB+7AKz6D5+b3XUxz59mpVjNxu3XbRw2jAG/jidhcME4q9pvD+5tOzLc4p8hY3+oX/W2aaFvIBCBFg==,iv:SQF0ADqKSOSADtFKaw+qB1qu5rr6lEh1+H7O3atWAsA=,tag:gIuwrKhuRAcK4KFnZkIeaA==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbWthUEpza1h4bmlTSGE1
        OGdTMHlONXVCbDJ3OVVzZ1lZdGpKdmdGa3prCldqdmlvTDRpZlNCNFV1NWpmbE1j
        U0xYazMzalZxcWpuWHMzZnZPUnpuV2sKLS0tIEc3UXBMUzc1c1JPTzJvWjdtZGd5
        bnRuT0xRbWZEbk1UN0VDdzFuZFkxTTAKh/ap5McNux70+EDVZ6XBHmnK31QhI+eH
        Xj3FdBMVzeS+XM/YCF8ytZvahfPjDk6N7yM8h4qILnMMdsJYQIqnnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T01:20:38Z"
  mac: ENC[AES256_GCM,data:hQUcaN1ty+YKCdwDTVmvaZtRMc4Fs84WnqGMDwgi4OT7LuAhh1Zdo2N+nRkt/Q1zNUAtZwJPZtegkvT5kkbK3o1/7YCMfQMyPz8LjgRrT1/M4G8u3BdxOAC5DxZ7h//U7YLRgSadyVZ/tL6HHgyoJRBN+/+FALSRqhH296EpAB8=,iv:UCzyyDCaYJcjnCnfbrKnjfTNXVsPVUTyYsuJLrfXYNI=,tag:aYlRfLgj7fgjpix9T+hfRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
