---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: artifacts
spec:
  interval: 24h
  timeout: 5m
  url: https://github.com/cloudnative-pg/artifacts
  ignore: |
    /*
    !/image-catalogs/
