---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: samba
    includeSelectors: true
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./smb-config.configmap.yaml
  - ./tcproute.yaml
  - ./user-config.secret.sops.yaml
