---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gateway.networking.k8s.io/tcproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: samba
spec:
  parentRefs:
    - name: default
      sectionName: samba
      namespace: gateway
  rules:
    - backendRefs:
        - name: samba
          port: 445
