# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: samba-user-config
stringData:
  #ENC[AES256_GCM,data:13ETH8YMriTwvaf0DdvZag==,iv:kj6B5XeFbplYRZlmWTE2M3IwmV0rNcTyOl74CS9WtoU=,tag:0CEuWxvFYfiPSQ6GIzCPjw==,type:comment]
  users.conf: ENC[AES256_GCM,data:fMExMZ7nz7jb8ewKzp2olZozUbrdoO2/XnctKzR5U8lSnVc7sJ3B8/1FZzoJ03GCuN5KRImTZeLjJlDOPaanKx8snaDspWW2++xhkgwymJLnwqw=,iv:y1+uwvk8kgIK1ZPYo7LW6gUjr3LVrFx53HP+081Cu+k=,tag:Nko84N+3QtSh5YLGiHuQ3g==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMUc5b3BRcmFKVXBha3pj
        akYxMGVONTcvM0R6MXNPUW5DUTRaZ0VwV3c4ClVOcXZKSFZzV21aa2d3K1VSZDQx
        MGdUZWVxWUlOV3krVHNwSlpWYjZkOTgKLS0tICtyazFoV1dyeGgrNkRWQ0Nrbjdx
        bGdOcGdBalNjcUFaaktacVlINUQ3c0kK5gv3gXclPS0dO2XL2oxkKzhPeZmj3aSY
        HKeHDHgegoX4qObpLab/7a1KfAkCYYND2PBeAqDvZLrzwTpH5FAKsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-08T03:00:25Z"
  mac: ENC[AES256_GCM,data:RW+g8pjrAWmAHKapE3MX0gpT8LM4Cq5O/mGeR75HV1DDx8Zs1C+LuN+jyb7IwJp9qpdxpFIm4/oQgqPlWHJ49uercllP3m1r/nBMB/Vx/yLAWVvbwB569zwdVZaomUoFnDK3JD7KRszbxALe3+e6PoqdQWQGwPm1kp0H0y9O4Yw=,iv:CdeDrsyjK2FvarlODU4Ief7D7KfvtvS1AwJHYrvZSM0=,tag:BqQhVZyiwH9J4tuw2J1mvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
