---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo-tempo
spec:
  interval: 12h
  timeout: 1m
  chartRef:
    kind: OCIRepository
    name: tempo
  valuesFrom:
    - kind: ConfigMap
      name: tempo-helm-values
