# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-authentik-auth
stringData:
  username: ENC[AES256_GCM,data:7yGa45gQQAU0,iv:NCfDpA4EQSJITpNZyJOA3nOHH5Hrnaip0EkycViMJGg=,tag:KIT1YcnXNepdpx+BPCxchA==,type:str]
  password: ENC[AES256_GCM,data:ROqkDFn1kC02,iv:g185FNdpwNRC+BsklVYHh23kmj0y2bhFu4163naR4OQ=,tag:ix1adfQsxv+Es0nkR2M1/A==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UWZUVGQ3ZHhLbmdzaUZY
        QTcyR3BrWHlZOUhxVjdkMDV3Ry9MNjBnTTJnCmorbXZxMXQ3Y0toOGV0c0pPQjZY
        NENVOWZ1dXJIVHRXRWp3ZHBPQVVyODgKLS0tIFp4T2hkTDh2cW53alRXTldja0xo
        TklUL094eHI0dVIyYzJCUHlBSUZHenMKi56/Z0avoCVNPIeYgfeUb4SJe25/q8Mc
        0nJ7SzYmreHrJ76R98jvVTJTsPjoliSjhGws9mMDA8Lxq0OijweovA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T15:35:40Z"
  mac: ENC[AES256_GCM,data:QPThThEBMmbkxffcAuUYjpyPyzCYImn6LxIeUDxdilTSpdaHMhwK2tNwpWbnjNoVG0JuLqwqihywlVkUOKH8No+FFhQPYLR4GCtQf6veMTVwW8eX7CViy1ZmUxx+P+G5t/8vD2dz1i+9ne7VujgZOKhiDlAZeF9xfnL3Nff/vuI=,iv:bxxFZozPYGBFimQKL3hU9yBmsagwg3SKsEK5ep/AjM0=,tag:nM2v1v3uBJKgj/GGtdO31w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
