---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./extension.dashboard.yaml
  - ./istio.folder.yaml
  - ./mesh.dashboard.yaml
  - ./performance.dashboard.yaml
  - ./pilot.dashboard.yaml
  - ./service.dashboard.yaml
  - ./workload.dashboard.yaml
  - ./ztunnel.dashboard.yaml
