---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name aria2
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      name: *name
    spec:
      containers:
        - name: *name
          image: p3terx/aria2-pro:202209060423
          ports:
            - name: main-tcp
              containerPort: 6888
              protocol: TCP
            - name: main-udp
              containerPort: 6888
              protocol: UDP
            - name: rpc
              containerPort: 6800
          env:
            - name: TZ
              value: ${TIMEZONE}
            - name: UMASK_SET
              value: "022"
          envFrom:
            - secretRef:
                name: env
          volumeMounts:
            - name: &config config
              mountPath: /config/
            - name: &downloads downloads
              mountPath: /downloads/
      volumes:
        - name: *config
          persistentVolumeClaim:
            claimName: *config
        - name: *downloads
          persistentVolumeClaim:
            claimName: *downloads
  selector: {}
