# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: env
stringData:
  RPC_SECRET: ENC[AES256_GCM,data:+fcOvbz4rOcnvJmUkzyg48ucVlKbGC5lkSb1W9XvIWXtFC05Yt08IJKaUW0=,iv:Tcs6F+LSRgnOQgxhcl2L0hB2YwMeYYWdKijGtFW1NAQ=,tag:kq32Si2anZn2Vw+8P+0kQQ==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UVBQeE5KK3NKQWhVQ2RG
        OXFiQ3dEL2pja0poODF2MnNkMXVpMHZVUDBjCmRadkdIYXdVamRkRWJkVks2bW1m
        ZGtyTlhwMlhSV2FsUGdIWklDc2VmcWcKLS0tIE4zQkczWmFKdmxGcncxQ0J4SEk2
        bHEybVNvTzZWbldtTnNTNkhNN3g4aTgKgqZT2l0uzjnMQ1l2BfnU+CsUPZc5hdzS
        ybyAh0wFq7CxkrzQwJB44viw7NIoVUOl/iTk55WIJxfWvQxrlxfIUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-08T04:36:46Z"
  mac: ENC[AES256_GCM,data:egPqVL1wLlj4w/S/+/5c1NnkkWhKpSqOJQS9Cpz2PdxTsog0zUhaMUhBVS+LJ0sivUEyXlGGdcqdtWhuvsrGvIs0Sz9riuMPiQnlk+cleE6Jvpyboad0n5ktXumSSM0/YI9O6vnRkg1IL1NJ7j+GdS60a/GCHM5UFZGUsgMYmaA=,iv:PMog3T8zchXMto/bhSM7CH+r2rRQv+xtZobcwKKn++g=,tag:Sqka5LrVOaX7JUfVwRw2ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
