---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager.yaml
  - ./cnpg-system.yaml
  - ./gateway.yaml
  - ./istio-system.yaml
  - ./minio-operator.yaml
