---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name filebrowser
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      name: *name
    spec:
      containers:
        - name: *name
          image: filebrowser/filebrowser:v2.52.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: &config filebrowser-config
              mountPath: /config/
            - name: &database filebrowser-database
              mountPath: /database/
            - name: &aria2 aria2-downloads
              mountPath: /srv/aria2/
            - name: &metube metube-downloads
              mountPath: /srv/metube/
      volumes:
        - name: *config
          secret:
            secretName: *config
        - name: *database
          persistentVolumeClaim:
            claimName: *database
        - name: *aria2
          persistentVolumeClaim:
            claimName: *aria2
        - name: *metube
          persistentVolumeClaim:
            claimName: *metube
  selector: {}
