---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: filebrowser-https
spec:
  parentRefs:
    - &gateway
      name: default
      namespace: gateway
      sectionName: https-wildcard
    - <<: *gateway
      sectionName: https-wildcard-local
  hostnames:
    - filebrowser.${PUBLIC_DOMAIN}
    - filebrowser.${LOCAL_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: filebrowser
          port: 80
