# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-clustersetting
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:uoPMqX6q0Z0U,iv:nhdajE2t3JqVesMOmq5Pz3bAjtq3sUOk10VKlOHMA4E=,tag:iHy7i5rxBgvF6zGPNcpHXg==,type:str]
  AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:jBGjBYPJlash,iv:eT3/NurC7wwh6n/26Euz9J3w3ukT5qkpbCl4j8KFLiY=,tag:DsX2hW1hFTxneQTaCXaLxw==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscUh1UU84MnVvRmgxMndM
        UEQwRlVMdnNnZFJyanVld21nanFEbGNVQ1Q4CnBzNk1RdnVSTktxL3hhZDlnOCsr
        M1RNNnRlMlRhb2FJbm90Mmt6RXU4VVkKLS0tIFZ6MEtCU3RpMUhlYitCeTQ1NzFK
        cXNVc1FDSXNDUno0d2hwNGRGMngxc0EKBpMsoEIe5oimqvQqtN6dZfcxzdyUmmzj
        Bi5/Gfvvxwcu2GhoBa6hUACzoEAAjGLyP28EkzpDZqIbxPjpp2qWAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T14:59:32Z"
  mac: ENC[AES256_GCM,data:y/UtwhFpJhKCzeOmylCvIeD63fEpFVQFstcrRcyOUalxEDNCD8TF3J+yLIuC6LXXpfDv0mOsFy1BwPnuqXSNRh53XuzZsXL+e717Ld/yFRVQJLf1nHHaJC/pLURYhV47M+XWnezX/LaLADMwTg+Dwir5/wS3b57r9zLZMelhVMg=,iv:BS2ES7EWedKKEFT6nAES978ns/ziqn4z2AdpX7gkVi4=,tag:xfwUgO0EazZObaohB+RJig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
