# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-clustersetting
stringData:
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:ytzF/kHWGDrO,iv:REF1CooQVFZF0IGD2oN6pFweSy5gEkoHvGjPqhNXKFU=,tag:Rl7sZW8xCorJo1io62cHbw==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:npoZXB24En9g,iv:7DuoIa+XlbgKDbyg+LgjolvoosFGmznptWLSCHEcKIw=,tag:1iN7ast52DuPK0OJh0smpw==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:GoSO/gIBOXHQ,iv:m6iXt4Vqo27jCfqD6Yygk3eCU/hxdujkm4sDTDosbeQ=,tag:kXP9ATXfB3cG1gRW6V7XqA==,type:str]
  AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:N3QxROewlzJi,iv:j0eWtHnnognYZOgBu3qTkuNVHiky6VPzfK3ViLzQu8o=,tag:Dn4XBrIg9c949PWILq30rA==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T3VneUNEVklNRmhIYVZr
        cnovWTZlMHJoY0hTc2YzZFNBc3Roam8xaEdFClVSTHJSQ2paNEorUXM1MkFwY2R0
        c3NRUnMyb2k0VkRaVUlkalZkOHRwN3cKLS0tIEZvUkFPS3VuU1NDaFJ5c0xHT29C
        ZWVENTRVWUdiVDJOV3VvdXhDQ25wZEkKKCZkTlCNCfEDkiaCZYzpYkQ7pvM6KSvB
        5wmF1we2NiSKysD/OONfp8fgZ+Jn6SZzhi7u51/qmJvknlgPYNvEzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T15:01:22Z"
  mac: ENC[AES256_GCM,data:O4EhhT83C5uJKD28t4ZP6i25aqW7jaXlbl46vBUmiRSFQ0bOySLvomuyERfLhiAMyaww7xBdx6hKQejrE3UY+BYUGG0CTpfTq1TTA2qfiHiNHs7VszkFO31sFLxShjXY6aFT97Mgmeslm5FquYbFe9qpNQJBcAHvQtH+AvbkyhY=,iv:bcK888w5pEGTlhMbnIpHlxySKIVY/WGor4NtmueAgtc=,tag:CdjP4Ac2x3JeoxX+YuZNGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
