# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-clustersetting
stringData:
  GRAFANA_DB_USER: ENC[AES256_GCM,data:8Gw+nNnNDg==,iv:JAcwXyMvPHtrhqRVx4syzuEUUYEzsNauEJuT6AT1sk8=,tag:dGUp74ajpuXrdSiDBi/tfg==,type:str]
  GRAFANA_DB_PASSWORD: ENC[AES256_GCM,data:H7WBk9qlcA==,iv:SqHQiUX2IT4JCOMekEEL6gf2+AszghEu6bmE6Lu1esw=,tag:UlisGWIj2dRVRyfb88R1mQ==,type:str]
  GRAFANA_DB_NAME: ENC[AES256_GCM,data:B4avsIWBIw==,iv:sNxCLotXuwcmye+USaumxeLCZcerx70lGAAjEE6amJw=,tag:cTDMkyRX27KTawv/OO0IzA==,type:str]
  GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:EDFNZHD9Gw==,iv:twzKG5JlJkFaP9QzBOnhi3psYNCotMJvIQjoSLFHEiE=,tag:kf+tubQpu2Jmovu9xEa5Gw==,type:str]
  GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:JGhgHZOwtQ==,iv:1moi6gOpIVM22OTz0px0O5TIpTpBVS03FMpbX4fcAlU=,tag:qG0O7+bqxYniKIrJesbjnA==,type:str]
  GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:OeH8AelPyA==,iv:VkOGp9x1P8j1NgDHmfXAZWogX7IhLoWhh2elF8XqM+I=,tag:lB4o0WS/2glurRP3wmySPQ==,type:str]
  GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:GrpTXht1eCF1aNYLhWuok0Dw7YgkrL9xbegRGBH0sg0=,iv:UgURGAJRZBcxCnxGn2eG3t+2V1H5OskjUggu99h1ZAU=,tag:qUmMh0rMrazVwV2EiMN9pA==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa0w0K292UlJKcHZ1WE4v
        VjRtdkJVV2NaZU5Wa0U4a0xFRXgyVTNoMnpnClJCaVlZakZYZldRVVArQVJXc3Yz
        RGpxTkJQTXlUUW1GSGFqZFpyRjBBcUEKLS0tIDQ3VFp5ajlsejVhV3RWSmdyWWNV
        c2R5RU1vbC9WZVlSNk5Ecndsa1E5amcK+1pxdX55k1oYxELU8NN/ysay3ADda0Qb
        9ZaF9mM750AxavkGX7JqmKdV3zcxTN5rUfBAoFsJ+jahSntDMWJ+hA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T10:32:39Z"
  mac: ENC[AES256_GCM,data:FAHwR0ZHaKi1svljRWpjeyW1FzCZ/BzEgdMXh7gGrd8EYH5Z0/FBplTwUOdaIrsHjcTRrZRmKIwGFWoErv3+/Fuu4KPVyqFz2kj58HeyPVKJTcSWI9w9FTsrBdXF5c6SexwFwhqdbswAOmp0wee5x//LOOCeaK/9UdabVhDMirg=,iv:lA8UXMxcC1S0DTxdhmZQXCp2QGyBnzXdejfUuKeyUss=,tag:UVFMUIFT82px5jVhaD/GUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
