# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-clustersetting
stringData:
  GRAFANA_DB_USER: ENC[AES256_GCM,data:oxeV7gpr+g==,iv:0M74W5EMyIewWcZe43FQwGWUE3+HrCllVTfAAKcf4Yk=,tag:k3AHFp0mV31zuSVq8VifJQ==,type:str]
  GRAFANA_DB_PASSWORD: ENC[AES256_GCM,data:Ow+Yih63Nw==,iv:EzKC03vZC0N7isqhzFOm0lm8uHO0KKUJ8wXa8h+vQ/A=,tag:LXlPNgZrsIQ9mXyuLZpPxw==,type:str]
  GRAFANA_DB_NAME: ENC[AES256_GCM,data:AaN5Q0uFxQ==,iv:aEp6EbVG6d0IvYrVYcQVGuFWDfzS4yWvEYsfh6jE73U=,tag:hpEMiuAxxRbo0qzqwxNeIA==,type:str]
  GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:5DAHpStV+A==,iv:oQyJJlyVEgf3P3/w2iITrn3EMIzrMAvCfIh0nQYfYuA=,tag:ZLlSkOZkVDveBfOAhBUKYQ==,type:str]
  GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:SLPMQC7CdQ==,iv:P6r0hfFysnF0fRqtnqKXhv9TlginyUMAZ4wmuQjpu9A=,tag:WlJ/fwopqEsSDo/i48p3ag==,type:str]
  GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:TIf/8LIO3A==,iv:18kRZ2A37B7LG5Z0SFmkpsYoAoEgCv788HXyJrEGFuM=,tag:pZc+fZ1P5z7gkrJU8BVQfA==,type:str]
  GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:nn+y9c+B4A==,iv:JTCQC9V/cYJVHIzsFft2PFsODPkRo5puhy0AjYXN6yk=,tag:o74pp8U/QtM5eKqGshXy8g==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVHpoSzBtc0NQS0ZNTHZ5
        VjBpS09pK2FiVGRKemxRTFFDYUV0dTBld2lJCjkzQ1NObjczNG1yZjZ6d1lUcVo2
        V0U0U0F0b2JEWVFBbDVhTk5YNjFtekkKLS0tIFA5WVloU0pTQ3hkaGJGeFkwWThk
        eFgwTUxTYUMySEdaWmtjakhtYVR4OXMKxz5+OhQkOvpleINOuzMoQr+0uvF1WcYX
        qVWYfR1RoGRdsXcBfty8XYpnjI4gAKwNTR2BdDGrf2ycxorFSwYxzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T15:04:47Z"
  mac: ENC[AES256_GCM,data:3ryGPSP5hPyItgH5gPxCVRi5EekYsI2NlErwi6bMopb4JuQZDAQ62QFu/8qQlp6xAKXLgxpVzcz75sTjcg0NsAHFvkm64R3nNXD7+vJjmncdyWOJZgcoj7yJuXpRjMjzdnSIZBDKgHTgfKJ0C9HhbW0eqA0nwVMdi1GeFvQOyPQ=,iv:Dbdr9kty5xzKFZzx4JrOzrx/Bg2ie0wSk8jOLGcXsEw=,tag:vG5bojHicw6MmFcfdjL9pw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
