---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbgate-dbgate
spec:
  template:
    metadata:
      name: dbgate-dbgate
    spec:
      containers:
        - name: dbgate
          image: dbgate/dbgate:7.0.6-alpine
          ports:
            - containerPort: 3000
          env:
            - name: SKIP_ALL_AUTH
              value: "1"
          volumeMounts:
            - name: &data dbgate-data
              mountPath: /root/.dbgate
      volumes:
        - name: *data
          persistentVolumeClaim:
            claimName: *data
  selector: {}
