# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: dbgate-env
stringData:
  SKIP_ALL_AUTH: ENC[AES256_GCM,data:VA==,iv:3VC+3pVsME88emoSvysOzrSZYVJgsnwnqrFcCzueVNE=,tag:yqHUj6KQXx4WKLnMb4L4cA==,type:str]
  CONNECTIONS: ENC[AES256_GCM,data:jXwguOim0+FTLe3TuoKjLLUedKPkOw==,iv:K/z0Zp8oVw8w/+rbD49NZNlkj1Q9gasjqJeN66hSF4s=,tag:4lGczWAQxfwkqnVaQ4rKKw==,type:str]
  LABEL_kite: ENC[AES256_GCM,data:aKnDDQ==,iv:QMhr0vw6hH3B4kGaxpyMhfuPUYGzlmxh9HaDsgPNWWY=,tag:oiJFrpQDiIZake5UoF4LdA==,type:str]
  URL_kite: ENC[AES256_GCM,data:woMKfTFrNnC4cbhoozQmdiD8de2J/Xjv2+ZHOuH3ogxtB3pr0oQY6w==,iv:IBbmPUp7R4cEARjeC53OMOJFODmbywjZXcu8ojd1L1E=,tag:xj+G41EnuUtA/coSgmifxA==,type:str]
  ENGINE_kite: ENC[AES256_GCM,data:mHnYe19lOGWUEpnyRsIxwIxwuPCC7C3euLGbj04AnQ==,iv:PKDCWMu1qZdvu7Vz96AmS/RfH90u01KCHTsLd3R1aqM=,tag:PJ7dxcFwGT77+Ec7TGyYWA==,type:str]
  LABEL_grafana: ENC[AES256_GCM,data:UKt05S+W3g==,iv:hPHSeag3hG2Qmok2cFHPq2/LF7u1Uw8PLF+gKUKLjsk=,tag:q0zVvOvql+Z/DzofC93fjg==,type:str]
  URL_grafana: ENC[AES256_GCM,data:mCvvc8cf146Fr1OwDUD8TjrobQcvcL/cuQThGx1ZeQlc9qwwdB/reueWIHGO5Vve4eCw4E3k8hruudBD,iv:qRCTHCf9r+Hfdai3QSkCqaA6QWlsw5ptWe8lmGkhjAw=,tag:UGGPFGxQTNJaDDBx9OpEEQ==,type:str]
  ENGINE_grafana: ENC[AES256_GCM,data:Bcr7F0o9QfEmFT5mSDQ5U28sa+6GQBcQw09B6C3D5A==,iv:ueWZELuzWQvkb9LSVPqLhZLSTMhMUG0ihYJyZtCwTi0=,tag:Y/8clOc3Ir1roBZ/YOrPHw==,type:str]
  LABEL_authentik: ENC[AES256_GCM,data:eDFTujUFijkC,iv:wIhF21jBPqUEg9sSeYfS1+nhGGCTpnjNwIzp+FCwtl0=,tag:6n3ybqohqii4WZb/UKYUfQ==,type:str]
  URL_authentik: ENC[AES256_GCM,data:kY9vq1X2b1kURIsqRvLQUdcBeaRFnTJ5YbvwI+ZzjT+FDTYC7khYysR2eqY0tMCwbpu6YfiAbhHuVZDY,iv:okqwLyroHzVITCjDJUZVhujI+WfU5JNPluAmnmhCS1Q=,tag:VAQRyXuJOmd2YtMD6zahhA==,type:str]
  ENGINE_authentik: ENC[AES256_GCM,data:nPD+cBVlBIT+DstH231ldUI8rDShVwtj7/xvhnFOGQ==,iv:KoE3yNtcfimfMJgc56LZ9MWKSOb/ANEtRw7MGNBYHdo=,tag:QX1vkGSnWDOBogNJWQq++A==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYnBLNUJnYXBsdUVkYkxS
        dk5hQXFNTGI2TDZwbVpzVEhqNGM0ZVpWOTBFCkpTNlpQUkJwRU1NWVVjWGp4REFm
        R2preVVHemliV1Vlb1IrL3hNRnp5NmsKLS0tIDZ2cFhoUXB4eERBWXhVcDV1Nm1q
        UzZlT05DQXdtN2ZRY1RsYXlVZmJobTgKIHV6HZ0XqfOQ080sITqbgdf2XxGLzNhn
        iwn7DvkkFmEhkDwDwxGihGUQ64lb3pC/dAze/LETtJ6lN6ael7GYvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T06:20:05Z"
  mac: ENC[AES256_GCM,data:bCiyNYEAJOg4gyXGPDdGIBKadpwDGuk7tl5B1rlvLHgZb6lcqZmRE0V9Eok58ES99puHxdj+RNZDWKro0cnJ6hNTtgbbpHihMz9FfByOaeEmNgRRTbtjM1fwh4fvLHhIEBp07EBeaSv3A4kyQUmLiXjgmrty+WRviVsWY01GiJ8=,iv:lE1VuCB5S2ma9iqRM89FOrB284WbM+4S3goqGc6S9Yc=,tag:sQlqEOMnWlQ0iCN3wAJ64Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
