---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./minio-operator.yaml
  # - ./redis-operator.yaml
  - ./authentik.yaml
  - ./cert-manager.yaml
  - ./cnpg-system.yaml
  - ./gatewayapi.yaml
  - ./grafana-operator.yaml
  - ./monitoring.yaml
  - ./reloader.yaml
  - ./traefik.yaml
