# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-r2-credentials
stringData:
  accessKeyId: ENC[AES256_GCM,data:kFYcIYI6+3jDMXM5ATRHk+swN1tMTiQ5foo3yIWliBo=,iv:XMMv1aptw4lDFIvS2KuUUUTZ1ACFmZFuvXrRqIr4yPg=,tag:Nzf3lpSMr6njTNY4ZzjLcg==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:m6mDd5gHgJHkiDKdoWwQOwCvLpOA8UJ6YiA3JDTgSoNEd7Iea/6935XiTStvAvIWagRCuiIfEM0optEsBSqpUA==,iv:9ztjQnQqyvdQXnYJrNLumSFYeDxyq2usDIhbmhUqs38=,tag:pT5waAz2j2UxUNlcd+wcpA==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMEdZcjlqL0xMUlJqVTBK
        b1g1WExrNjkyaUJFL25keXh5Ym9kMzkxL2owCndBREswZVFBVTlrTXlCc3FLVkFX
        M1RxMWRmRWx1N1NjWGxjRUJvT01QQUkKLS0tIGFWbGRSUW5LZXB4M3QyVHpDLzJV
        eFk3MHlCZnNKUys3UWFPYXcxU29kQWMKMOCkA8p2kuPCPzuxfK/2G68EjZZQE1/n
        6m5TpcYB7Nl9YTTjbFYlWEwFn1NW3h7bBO+0D7HmyUxNoUaG+DDKbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T15:39:22Z"
  mac: ENC[AES256_GCM,data:Cex7y5R0GFmsyH4Hh1KjjwV99Vtr6IYLvpRyhC/fmWytJYG45VYZIFUK7wGQrtc8upAhpUP5Wgt4xKovz85nI2LcoNfeiVL0Lt0TfylE0RG6xXGal0Yz9wGCfIcjS32i9ycrsPCpgwv0ZwhGbJC70uaER3DyXA6SHcAfLHs4mVo=,iv:jLDcpililFUsGnxYACkcNZGbYBTUbsghyJr7IzaJHL4=,tag:kvg4TRQP9O5pfPYRLJj0Lw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
