---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-cloudbeaver
spec:
  interval: 12h
  retryInterval: 1m
  timeout: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: kubernetes/app/main/cloudbeaver/
  dependsOn:
    - name: infrastructure-controller-gatewayapi
    - name: infrastructure-controller-traefik
    - name: infrastructure-controller-cnpg-system
    - name: infrastructure-config-cnpg-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: clustersetting
      - kind: ConfigMap
        name: clustersetting
