# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-cloudbeaver-auth
stringData:
  username: ENC[AES256_GCM,data:+rxqPU4EZcv1HK8=,iv:8LIWYsIaNtJGEsyR5L4IsNVQ1zrvLzWnlmoTNeHMHPw=,tag:I/qIMRBemt98ix7VKnAEZw==,type:str]
  password: ENC[AES256_GCM,data:yKQNCB9qm4OKykU=,iv:qEC0TAcFEKQr9z0AqTipuZSKPxgvpMl+pKpLFth2P9o=,tag:BX1Kshu/1lH0Iia36MVheg==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cGFPNDBLRFJnalZRbkR5
        Ukx2M1VaVEh1VlQ1ZWxjcGZoV05RUTk3YzFFCk5rekMrUVB0MGZxY2ZBSzl0N1E3
        eVk4QXBKWFFWQ1UyUVgxT2JsR1hPcGsKLS0tIHhLajZ6ekpWdlVOMGtYQTBPcUtx
        NC9JNDR0VFNlYUdUYkVNRUNVaW1tTmsKPS9wmVIXc/5a0x2QPG3ZkuRycM2JYnN2
        nRsromxk9L8SG7FGQAbyc2MZbFZH8trjzEXKZUonV+UUJj31NMk39A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T04:19:13Z"
  mac: ENC[AES256_GCM,data:9StwnLeHQVaGzLdi8CJwizkftvKy0ZSBZNRnh6Zfn+/PoVUeNS2Q6N3bxXSSwLU2JPCofaQNLxUE5cYpmLvi1we2qI102MR1iTkYa/BL9xzMPlC0dQWJIIboaWaEUcth9XMWH4gSuvIKpajEPAASMg2r9GYoT1No2POCzA46e0Q=,iv:7CnZ7Yo3oZVifVYuUO2Au6jHOp190C9Id419tG7mZnM=,tag:6KT3J/1hGz5UTZZyzlLl7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
