---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlas-operator
spec:
  interval: 12h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: atlas-operator
  install:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: atlas-operator-helm-values
