---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  interval: 12h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: plugin-barman-cloud
  install:
    crds: CreateReplace
