---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name cloudbeaver
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: k8s
      sourceRef:
        kind: GitRepository
        name: *name
  install:
    createNamespace: true
  targetNamespace: *name
  values:
    cloudbeaver:
      image: dbeaver/cloudbeaver
      # renovate: datasource=docker depName=dbeaver/cloudbeaver
      imageTag: 25.2.0
      replicaCount: 1
    backend:
      internal_db: true
      cloudbeaver_db_driver: postgres-jdbc
      cloudbeaver_db_url: jdbc:postgresql://postgres:5432/cloudbeaver
      cloudbeaver_db_user: postgres
      cloudbeaver_db_password: pybhqornire
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: PersistentVolumeClaim
            patch: | # language: yaml
              - op: replace
                path: /spec/accessModes
                value:
                  - ReadWriteOnce
