---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudbeaver
spec:
  interval: 12h
  timeout: 5m
  chart:
    spec:
      chart: k8s
      sourceRef:
        kind: GitRepository
        name: cloudbeaver
  install:
    createNamespace: true
  targetNamespace: cloudbeaver
  values:
    cloudbeaver:
      image: dbeaver/cloudbeaver
      # renovate: datasource=docker depName=dbeaver/cloudbeaver
      imageTag: 25.3.1
      replicaCount: 1
    backend:
      internal_db: true
      cloudbeaver_db_driver: postgres-jdbc
      cloudbeaver_db_url: jdbc:postgresql://postgres:5432/cloudbeaver
      cloudbeaver_db_user: postgres
      cloudbeaver_db_password: pybhqornire
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: PersistentVolumeClaim
            patch: | # language: yaml
              - op: replace
                path: /spec/accessModes
                value:
                  - ReadWriteOnce
          - target:
              kind: Deployment
              name: cloudbeaver
            patch: | # language: yaml
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: CLOUDBEAVER_DB_BACKUP_ENABLED
                  value: "false"
