---
# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json
server:
  proxied: false
branding:
  hide-footer: true
  logo-text: K
  app-name: Kevglance
$include: auth.yml
pages:
  - name: Home
    desktop-navigation-width: slim
    head-widgets:
      - type: search
        autofocus: false
    columns:
      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Kite
                check-url: http://kite.kite:8080/health
                url: https://kite.kevinnitro.id.vn
                icon: sh:kite
              - title: Grafana
                check-url: http://grafana-service.monitoring:3000/api/health
                url: https://grafana.kevinnitro.id.vn
                icon: si:grafana
              - title: Prometheus
                check-url: http://monitoring-kube-prometheus-prometheus.monitoring:9090/-/ready
                url: https://prometheus.kev
                icon: si:prometheus
              - title: Alertmanager
                check-url: http://monitoring-kube-prometheus-alertmanager.monitoring:9093/-/ready
                url: https://alertmanager.kev
                icon: mdi:torch
              - title: Loki
                check-url: http://loki.monitoring:3100/ready
                url: https://loki.monitoring:3100
                icon: si:loki
              - title: Alloy
                check-url: https://alloy.monitoring/-/healthy
                url: https://alloy.kev
                icon: sh:grafana-alloy
              - title: Keycloak
                check-url: http://keycloak.keycloak:9000/health/live
                url: https://keycloak.kevinnitro.id.vn
                icon: si:keycloak
              - title: Cloudbeaver
                check-url: http://cloudbeaver.cloudbeaver:8978/status
                url: https://cloudbeaver.kevinnitro.id.vn
                icon: si:dbeaver
              - title: Ariang
                check-url: https://ariang.mayswind.net/latest/#!/settings/ariang
                url: https://ariang.mayswind.net/latest/#!/settings/rpc/set/https/aria2.kevinnitro.id.vn/443/jsonrpc/$${ARIA2_RPC_SECRET}
                #   url: https://ariang.kevinnitro.id.vn
                icon: sh:aria2
              - title: Metube
                check-url: http://metube.files:8081
                url: https://metube.kevinnitro.id.vn
                icon: sh:metube
              - title: Filebrowser
                check-url: http://filebrowser.files:80/health
                url: https://filebrowser.kevinnitro.id.vn
                icon: sh:file-browser
              - title: MLTB
                check-url: http://mltb-mltb.mltb
                url: http://mltb.kevinnitro.id.vn
                icon: si:telegram
          - type: custom-api
            title: Cloudflared Tunnels
            css-class: "widget-type-cloudflared"
            cache: 4h
            url: https://api.cloudflare.com/client/v4/accounts/$${CLOUDFLARE_ACCOUNT_ID}/cfd_tunnel/$${CLOUDFLARE_TUNNEL_ID}/configurations
            headers:
              Authorization: Bearer $${CLOUDFLARE_API_KEY}
            template: | # language: html
              <style>
                .widget-type-cloudflared li {
                  margin-top: var(--list-half-gap);
                  border-top: 1px solid var(--color-separator);
                  padding-top: var(--list-half-gap);
                }
              </style>
              <ul class="dynamic-columns list-gap-15 list-with-separator">
              {{ range .JSON.Array "result.config.ingress" }}
                {{ if (.String "hostname") }}
                <li class="flex items-center gap-20">
                    <div class="shrink-0">
                        <img class="docker-container-icon" src="https://developers.cloudflare.com/logo.svg" alt="" loading="lazy">
                    </div>
                    <div class="min-width-0 grow">
                      <a href='https://{{ .String "hostname" }}' class="color-highlight size-title-dynamic block text-truncate" target="_blank" rel="noreferrer">{{ .String "hostname" | trimSuffix ".${IDVN_DOMAIN}" }}</a>
                      {{ if (.String "service") }}
                      <div class="flex items-center gap-10" style="margin-bottom: 5px">
                        <div class="size-h6 flex-1 text-left">
                          <a href='{{ .String "service" }}' target="_blank" rel="noreferrer">{{ .String "service" }}</a>
                        </div>
                      </div>
                      {{ end}}
                    </div>
                </li>
                {{ end }}
              {{ end }}
              </ul>
          - type: bookmarks
            groups:
              - title: Mine
                links:
                  - title: Kevindex
                    url: https://kevindex.kevinnitro.id.vn/
                    icon: si:cloudflareworkers
      - size: small
        widgets:
          - type: server-stats
            servers:
              - type: local
                name: kevblink
          # - type: extension
          #   url: http://glance-k8s/extension/nodes
          #   allow-potentially-dangerous-html: true
          #   cache: 10s
  - name: News
    desktop-navigation-width: slim
    columns:
      - size: full
        widgets:
          - type: rss
            title: UIT
            style: detailed-list
            cache: 1h
            feeds:
              - url: https://www.uit.edu.vn/taxonomy/term/83/feed
                title: General Notifications
              - url: https://www.uit.edu.vn/taxonomy/term/87/feed
                title: UIT News
              - url: https://www.uit.edu.vn/taxonomy/term/202/feed
                title: Study
              - url: https://www.uit.edu.vn/taxonomy/term/201/feed
                title: Student Activities
          - type: rss
            title: UIT Forum
            style: detailed-list
            cache: 1h
            feeds:
              - url: https://forum.uit.edu.vn/posts.rss
                title: Posts
              - url: https://forum.uit.edu.vn/latest.rss
                title: Latest Topics
              - url: https://forum.uit.edu.vn/c/ho-tro-doi-song/viec-lam-thuc-tap/32.rss
                title: Internship
              - url: https://forum.uit.edu.vn/c/ho-tro-doi-song/hoi-thao-tham-quan-doanh-nghiep-cac-cuoc-thi/33.rss
                title: Companies
              - url: https://forum.uit.edu.vn/c/goc-hoc-tap/cong-nghe-phan-mem/20.rss
                title: Software Falcuty
              - url: https://forum.uit.edu.vn/c/cong-dong-uit/10.rss
                title: Network Falcuty
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
  presets:
    catppuccin-frappe:
      background-color: 229 19 23
      contrast-multiplier: 1.2
      primary-color: 222 74 74
      positive-color: 96 44 68
      negative-color: 359 68 71
    catppuccin-macchiato:
      background-color: 232 23 18
      contrast-multiplier: 1.2
      primary-color: 220 83 75
      positive-color: 105 48 72
      negative-color: 351 74 73
    catppuccin-latte:
      light: true
      background-color: 220 23 95
      contrast-multiplier: 1.0
      primary-color: 220 91 54
      positive-color: 109 58 40
      negative-color: 347 87 44
