---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: glance
    includeSelectors: true
configMapGenerator:
  - name: glance-config
    files:
      - glance.yml=./config/glance.yml
secretGenerator:
  - name: glance-auth-config
    files:
      - auth.yml=./config/auth.yml.encrypted
resources:
  - ./assets.pvc.yaml
  - ./deployment.yaml
  - ./env.secret.sops.yaml
  - ./http.httproute.yaml
  - ./https.httproute.yaml
  - ./service.yaml
