---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kite-kite
  labels:
    flux.kevinnitro/repository: homelab
spec:
  interval: 24h
  timeout: 5m
  url: https://zxh326.github.io/kite
