---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: aria2
    includeSelectors: true
resources:
  - ./config.pvc.yaml
  - ./deployment.yaml
  - ./downloads.pvc.yaml
  - ./env.secret.sops.yaml
  - ./http.httproute.yaml
  - ./https.httproute.yaml
  - ./service.yaml
