# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-setting
stringData:
  GRAFANA_DB_USER: ENC[AES256_GCM,data:x6bGK4mZ1A==,iv:tHeXTUysPcp/tW4iEqgUme5iTAYcvL/O078Wu9SS6/A=,tag:A3LAwFxAhH9GmzzreSgPwQ==,type:str]
  GRAFANA_DB_PASSWORD: ENC[AES256_GCM,data:WDJsIClgBA==,iv:JrVQcqBMqjepaH7d5DZFPJSL1Tih1pLAOk+yBkWk3Sc=,tag:rPINySwnE9Gd6FMzSsVv4g==,type:str]
  GRAFANA_DB_NAME: ENC[AES256_GCM,data:eM/3gYt0jQ==,iv:7xwyctXsqVUZDadUyngosQEYhRGxAOmc+wXRWInupaU=,tag:knNLtrhvIKBeFQXSaQVwdQ==,type:str]
  GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:2Ze8Y+fVgg==,iv:6/tPKxguBDD9I2r0L9aTF+cbeC7eeVsTB8sIvHbHG9I=,tag:em8ulHPKVrkgigfaQiSr9Q==,type:str]
  GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:EgolhJ12zYMG4LQawIPcLKxP1URwvEU/5XEa1YBWWAY=,iv:mAwY4aDNxS7bTc9bnxn4K75H7kACQsOjsiewUmhY/jE=,tag:Ahf51O3AYPACBCdOD5SFlA==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR1lwdTNvRmp4eFlEVjUr
        V0I5aGczQVF2K0twY2VWWHV5eTdWaXAyUGw4Cm9JRk42TkQ1VDdhUFByTkpNZDV2
        OG8rK0NzbHNYdVg2N3IrNjR6WDlyOFkKLS0tIEw3RkZwQzBSdXZ4dDNKUGFUbXl1
        UG92dVRzbDZiQ1QxVGxvcXJHVWRxcHcK4/dxTk7oCbWLtcnBaHyjwcCwE/KUHiym
        Gmv7rcCbmHuuiHxT8IhRYtsq1GN35BjwsTqTNigXa/g7ASzbKy0eGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T01:53:47Z"
  mac: ENC[AES256_GCM,data:JxpugBhUUVSfjSE1SaEtf14PmutO8ccsuXpdwMyLntalhb943VL2wbKlGWtYxSv37pyFDyMFexK1rcrKjEKSJe96qSt9KxQbKfcMTjSCDtWiZgerlYHgS4VNbohrIM6ofDV4BRB0Q0otDj0PcS+EYcstrLPTDV/RE54x0fPi3+Q=,iv:1Lv+d/wzXG6RU3OyswG2plKlXzjK+p/gLTq7qYsDvfg=,tag:9+H6dOQyjcx35hBbO8iUFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
