---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name grafana-cnpg-grafana
spec:
  bootstrap:
    initdb: null
    recovery:
      database: grafana
      secret:
        name: grafana-cnpg-grafana-auth
      source: &backupName backup
  plugins:
    - &barmanCloud
      enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: *name
        serverName: *name
  externalClusters:
    - name: *backupName
      plugin: *barmanCloud
