---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: mltb
    includeSelectors: true
resources:
  - ./config-map.yaml
  - ./deployment.yaml
  - ./http-route.yaml
  - ./sa-accounts.secret.sops.yaml
  - ./sa-token.secret.sops.yaml
  - ./secret.sops.yaml
  - ./service.yaml
images:
  - name: ghcr.io/kevinnitrog/homelab/mltb
    digest: sha256:f8eb74270db25dd93ea8992ca8164856bed41c092d6e9b6d11f0597e3e85c486
