# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres-credentials
stringData:
  username: ENC[AES256_GCM,data:Hb93ZcHCTJPE,iv:mBIkrkuxT4iGUIEVUf8CPZ9N31E6ka6va8Cqa2U7I08=,tag:/ECRrMX0mFE17hKJWK1I1Q==,type:str]
  password: ENC[AES256_GCM,data:TlMyMDgRVG87,iv:Ex5UaLL4xDfEGFtxDdueaa0R0O9zG8Hf/mfwDL6hn8Y=,tag:bmTMWH4jq1DcgqjPeywuNg==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eUJsR284NDk2RURpbUNv
        dFFQU2VHd2xKZS9uRXNLNFVyMmlQVlZSYlhVClc5MzA2ZXFBSUFpSnd2TC9RUzhD
        ZE8yZStpRlRCUU9ZVW1UV3NWdWxlMGsKLS0tIGI3elNULzVHOTNoenBMMkRScE5R
        c3h0WnFMV2VsZVJhL2dXUlZKL1d2OGsKlZ8uE+3peoITfc4qUjOfXJkwvT+M1Xm/
        VYs6lGgvR5RiBqDueMZvtAcCyZjP7BouR4b13FOZD7QTgGtDWGD9fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-15T02:27:28Z"
  mac: ENC[AES256_GCM,data:60C+rUwhJsjH8sGhr/cXP7VaLtYwpApjSOsv4SR8IciZu/SdJsngejNzBxQkmyfgJU1Es8XwKEwHITykoS/3t0AyPipRz3w8mvXPqZSM02A2YtfPXlCfJLdRJmLe/ipAoU85Z0z2gcIwaz2Fkzg/+Z+oxVC+9hE3tVpy0Xlg1BM=,iv:9kDKtwRPvpptD5PvvUI3wehnEA31ZeFWgFlnxpa1FGw=,tag:avRblPgIA7TcIqI1E5bX8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
