# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
stringData:
  admin-user: ENC[AES256_GCM,data:SbjsKHP8Ew==,iv:nlz5a7lWZ0X8OM1EPE4odje/e8BWSwA13g9JlCPJfzQ=,tag:TCakFJwtSJFASywD5c5Mpw==,type:str]
  admin-password: ENC[AES256_GCM,data:5J78m97t8Q==,iv:QY9Ly0SK+u30+F6XPiJSnqxAF6amlfZ2NQYkNeJPzo8=,tag:0NX2jEaEQvJtSdxFJw0U+A==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM0J5NmxtWUpWaWpZT1lL
        Tmh2RzljVzM4OEZDM1l6M1VlUmZXRHFPSldjCnlyZ3Z2angrTmJNOEJBMzc0U0lR
        USsvSmFyUTNpVWlqa2hEL0RwWlFpbk0KLS0tIGtnUTJVMCt2bHVmdDZaTTlpaldW
        Z0h2WmZ5TEdTWnA0dSt4TUVUQll1NHMK4x0qIPPD1ebgCPkzohYblp4SxpF6pS5e
        tzXKF45AhGnCxvy1+PzNeYLn1TC/TYajM9tJB0AMtvAfIVg35sNkMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T01:09:34Z"
  mac: ENC[AES256_GCM,data:gJSjlQBA/1z751AUiO2IRoTWUuYXbnGWTdPVN9lVxrKDnLmJ+jeS9MOPD94kRRrvFqKfrPw84nnRZLywtFetYMo38rCz91VcMLLLiCJysuUpGWsly7Py8HRfoygf6TabCMWbqiFmtE8EiSn+1xo/8LgkDGvF5UyudPaIO08QpdY=,iv:kGJsfKxPBlYXamtrPTzw+scn+D7ikT6dGqVQk156DYw=,tag:HhYBzuQdTigQAk2achTp6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
