---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./http.httproute.yaml
  - ./https.httproute.yaml
patches:
  - path: ./grafana.patch.yaml
