---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/grafana/grafana/
  - ./http.httproute.yaml
  - ./https.httproute.yaml
patches:
  - path: ./grafana.patch.yaml
