---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-samba
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      name: samba-samba
    spec:
      containers:
        - name: samba
          image: dockurr/samba:4.22.6
          ports:
            - containerPort: 445
          volumeMounts:
            - name: &smbConfig samba-smb-config
              mountPath: /etc/samba/smb.conf
              subPath: smb.conf
            - name: &userConfig samba-user-config
              mountPath: /etc/samba/users.conf
              subPath: users.conf
            - name: &aria2 aria2-downloads
              mountPath: /storage/aria2/
            - name: &metube metube-downloads
              mountPath: /storage/metube/
      volumes:
        - name: *smbConfig
          configMap:
            name: *smbConfig
        - name: *userConfig
          secret:
            secretName: *userConfig
        - name: *aria2
          persistentVolumeClaim:
            claimName: *aria2
        - name: *metube
          persistentVolumeClaim:
            claimName: *metube
  selector: {}
