---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
namePrefix: grafana-
resources:
  - ./cloudflared.dashboard.yaml
  - ./cloudflare.folder.yaml
configurations:
  - ./kustomizeconfig.yaml
