---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: infrastructure-config-
namespace: flux-system
resources:
  # - ./istio-system/ks.yaml
  - ./cert-manager/ks.yaml
  - ./cnpg-system/ks.yaml
  - ./flux-system/ks.yaml
  - ./gateway/ks.yaml
  - ./minio-operator/ks.yaml
