# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-setting
stringData:
  DUCKDNS_DOMAIN: ENC[AES256_GCM,data:DRfUtS91dwk1GGGIeDIopp7vxXbUSZfk+Mg=,iv:6DbkHKGujRsd3FxDFo6cedQUvusFVD/v6CClG7DChu4=,tag:Z6P4qrmnHHvWo8ODSk+WrA==,type:str]
  PUBLIC_DOMAIN: ENC[AES256_GCM,data:Y/MNttHIp/5VJriBpXTYQw==,iv:XgBLM7DrSQKD33+Mj9oT5tIs/CmBqCG40EnYrKQ9G0E=,tag:GwbWWNF2nwo2TocUfKpPnw==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cVZkMDMrVWNFeGRHcHk0
        TmlXUkF1amxnSVhIeEtvT1JkRUdjdFEzbnlRCkwvSjlHa2lnSEhkbXRkazVCaE5P
        ZzdEL1JkWjg2ZktlNWE5MHRSSlRoU2cKLS0tIENhazVlY0N6SW9mSmNuZE5HMFkx
        bmZoQW4xcmpKTmRQUGlYaGVLc0c2OHMKctMuwo/Fnfv4HNQXnYYcdFzEiCV2I+OZ
        OlNv2EBd0r93H2iEFlSwJCsCYOIl4v0+K0HO0yhtan+QK4R5ULTdKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T05:02:11Z"
  mac: ENC[AES256_GCM,data:3T59HfOM5ncxsdUuBcXv1R5PCaiF27cNOBKZ5nU9lEhjpJuOpKqf5bMzCu6xhOVZMlsIJjG6Un7U+Ri+e2YhH+xCFmw7M3wPwAWFvRBV0aInC4vQAntIR9na61s8wLPoKyzITifSaeH0x750MEQJpxxTkui4Eu5+684jJ9vql5I=,iv:xDBsWyDTZaLTeyscp1coJuLxgoz+/OlTKNFSB1/jlNE=,tag:BusStnY2xpk1Bm1bwjrY0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
