---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
