---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kite-http
spec:
  parentRefs:
    - &gateway
      name: default
      sectionName: http
      namespace: gateway
    - <<: *gateway
      sectionName: http-wildcard
    - <<: *gateway
      sectionName: http-local
    - <<: *gateway
      sectionName: http-wildcard-local
  hostnames:
    - kite.${LOCAL_DOMAIN}
    - kite.${PUBLIC_DOMAIN}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kite-https
spec:
  parentRefs:
    - &gateway
      name: default
      sectionName: https
      namespace: gateway
    - <<: *gateway
      sectionName: https-wildcard
    - <<: *gateway
      sectionName: https-local
    - <<: *gateway
      sectionName: https-wildcard-local
  hostnames:
    - kite.${LOCAL_DOMAIN}
    - kite.${PUBLIC_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kite
          port: 8080
