# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: kite-secret
stringData:
  KITE_USERNAME: ENC[AES256_GCM,data:QVIPPtcnGkWZng==,iv:q7JS02kpCPNbO9/pfCfISV/ofqXTp+o0GApTMZ0MYLY=,tag:J/ecJhOVA7BuX9SXeXrQeA==,type:str]
  KITE_PASSWORD: ENC[AES256_GCM,data:q2hK/WN73VNBfpzA,iv:7uT7VWW6cNONqRVIodHsU9pW6HCmdLY3ay4ccsjPFyg=,tag:n4+n7f2eiWNsMrmt4NTRoQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:yrnRs21kbTymOSVSY4FMnuEgxH7kPvp7cC7nsJDCwtFY8j0zcq+tqraDPTw=,iv:T0hVHghz+SpMCCxDjk0tSXgSmblA/1HA+lnNC1M/vqA=,tag:wqRGk9f827UvgN9JxWYrNw==,type:str]
  KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:8MBOrYnkgzGBZdoIEJ4lK9EdhG5YFQcAxjRTKn8VP9oyTtRDAZJeZjbqsME=,iv:uqgAahclfUXan9HuexxfLgdQgYqMm/mhJZcg86TyYcw=,tag:wiWdcObOBqRGLWrCVAPijg==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUEFvNXJOdy9uYlM2Y1Ba
        azdMQUc3ZjF1MkhkcDA5UFQ1Z3ZhcTdDS25vCjQvd0Z2QmNqaDkrM1lXZHA3ZWt0
        RmV4UmR0SkdsNE91RDRMU09XRjVjekkKLS0tIGV1WWZDTzZIWFljN3Q5cmkrdUlv
        NkdYb2h5aWt5Y0l3bmcwNFpKTytrMXcKRSc8queRD2/dciNMapIAVZXlePQ7+w43
        OFXzkDu1WeZVeHlObH0T8t5t1u10C0WPNHvzysqUpXQAjsIkrkHwpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-15T00:50:25Z"
  mac: ENC[AES256_GCM,data:eKqNvf3ZdCpJWoMIRQotMbdyh9csCiMIjxIdvTYHDE/gwBE2n+V9T0Vzbne/+Pgmwyce0SQUgmC1d0MpxISxrajxKjUUgwpt6PYxDQ5GRbZodF8oVHRmXFu4zgrdigQH508Vt+c7kjHpVkBkxjkGTQM1yWTSZbPnBzkQ9SaQps0=,iv:v4yD6Zx+5MK5Mh59fKDeHpwNs/h2I2kgJBFMuI1KkPM=,tag:bsGVQrolRcfztHnBJR9UfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
