# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns-config
stringData:
  #ENC[AES256_GCM,data:L8yjttGd2MCWpwulPHvd,iv:ZatwH1pk0Hygcq6ZlTvoDDTMFKU6jpsmpfwqvpsOTR4=,tag:0z/r5B35XHIAADDhNxzxlg==,type:comment]
  config.json: ENC[AES256_GCM,data:qLABMMsgLaSe6YRnwIDX0ZlnSR8x8UmAkuUy+7rwKP3THV/OqqigRXC3QRRkecmLTPO0k4TqeujOfjG85RrCcwFcvbYUahf16M4PRS5p0QgHzDds0eajr6opymKPiWZtqh0gwGWIgDpBQvCGC8ell2Mz2shRuz1ieRP4R8YcC17szd88U8D7FIxrV1v5lVNmHBmMcDDyp+9jjC+MaJxQIzudVPPFBwZwhOqroAgGXLetcWq3JRnzgTmPAaxByKKKAKTKhvK0UOhKYDfpMFyPqSVYuBb2d4GyLhpDaNl/S89FPSKLDvUgdrw8CgMCVikkquRgBHwPuacTbUxT6oEurN1dWjPEn/JDyJMWZhyQ8skPQAZVcudFrjrdLl/OK3p/TIVdoODvvEv6dTrjdjS3qJ4Iu+74y/rImLFMgn+L/evahyCRQwclcA3X1cQLP/5mC2HwlyET9Sgi5wO0QEp/XLyppYJmLoWvDv6lXpQ8es44XL6Tqy/RZx+YXF5X1eXz5jMw+S04L8JGaXPMNq5PEFgA3SQbJ3xgTh6rBKI7XGGui6SxNo+R,iv:s3+I+7jwzTNfvBVyFlJsnvREW+Y0dfxwAZxAKQ/1rRA=,tag:pQovdnQ56Xd97ts4+G2qgw==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OWxNN2ZjcjhaUTYvV3NT
        RlRSZ1VyeUttYW93YS9IQWtnaU50K016NlhZClFzZEpMdmx4azZrQkRwSVk4UHc5
        OFpUUzRLRFFzcktnWjJyUkNKT1o5bDAKLS0tIGFTNitpSXhSUURaMGpxVXJ3Z3ZV
        RG9UdUJSOVAvK1pNUWp5V0ROVEEwUFkKYAH5McT0G0DPiB9GM8+mhnYKeMxbMomF
        Vi6z26tHzT7cuaNSt60ESPZzYVV+PGH54/x36Fd5VCtQdZPrjJtuIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-10T15:39:38Z"
  mac: ENC[AES256_GCM,data:kVwNkX/6fRk4ZuIS5JImiZSIfWFmyAeZ0kedrlvayTAg50mO5vIt28F3/0oGnKYCTgBavgMNXIgMeQVKvQtMiC6ObSC83FwozAaLPE+4vbVmlT2nDk17U1P8/MGZuKRJ+HlRa2FgNmJINdDhsKx9CHWJFqgzSTjMkgHZTUScya0=,iv:pNt7b0xV+soOhRGXHlDz3hO0qRjOnhFlbY1h4Zghy7s=,tag:VQoTHB+feqQCqT24gYu7Uw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
