---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns-cloudflare-ddns
  annotations:
    reloader.stakater.com/auto: "true"
    glance/icon: si:cloudflare
spec:
  template:
    metadata:
      name: cloudflare-ddns-cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: ghcr.io/irfanhakim-as/cloudflare-ddns:1.0.2-fix-wrong-ip-r2
          volumeMounts:
            - name: config
              mountPath: /config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: cloudflare-ddns-config
  selector: {}
