# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-alertmanager-telegram
stringData:
  bot_token: ENC[AES256_GCM,data:TR10Chg2zPoY083mpX8BluAXAsYLdPZOWct7MFsk8WygqYIJsaEyp1GwHlmYCg==,iv:K+o99hfdw7qPU1Xesyc2Rknw1jP3xJbuyTX7lvdPsrk=,tag:UfjpFHPXjdu5QozxA8dgyg==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpKzBwaFE4aDN0dEdlMTZU
        a1BuRzNoYmdQQkJ1YmhtSUNMc2pDRCtZUkJnCmtob2xySmM1L1gxVzROZVl5eVlB
        WmZkR0dTRjZaUi8yNUJlWW80TUhBdFkKLS0tIC9OSFhBV2tKUTVLeFRXZ0ZjclFK
        SU9JYUZETmk2dFo1MGJZZWg4eDd6eFUKHYHvqTRQZqM03AegQyow7DRXbPSyGyK+
        fnUuAexyUfSCc7p8Yhx43Pvliwv3kzjLT69CK2KNCRXQFGMq6j3PnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T14:39:25Z"
  mac: ENC[AES256_GCM,data:OuJuKqAZroYa9zJbteGzWMJb2fAuGJhBwKOG619c0M4kcys2aoc1Vs91bXLuUAn2S5HEBY2VcxK8RXW6P5Le/tDRpowSHRDinl70qoEFQbR6AHY0miKR1Xq4XEmzXsITA5VX3wb6ortzWsxo2KUGgm8BJwePe/ZDHs+OIj5AmaU=,iv:5NR2TIRqDCmHIysuAYXZNF/96zBAV54z72ao7XBuRyc=,tag:RA0PLaLr2ILJKTl3ITtVKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
