---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube-metube
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      name: metube-metube
    spec:
      containers:
        - name: metube
          image: ghcr.io/alexta69/metube:2025.12.14
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: &downloads metube-downloads
              mountPath: /downloads/
          envFrom:
            - secretRef:
                name: metube-env
      volumes:
        - name: *downloads
          persistentVolumeClaim:
            claimName: *downloads
  selector: {}
