# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: kite-kite-secret
stringData:
  KITE_USERNAME: ENC[AES256_GCM,data:UK6bkg==,iv:ZnuWaleCDR7l1bstqxJcs016Lc44faKAcmEu2sWpQkQ=,tag:/Kry/5ksXoXC5tnM52SluA==,type:str]
  KITE_PASSWORD: ENC[AES256_GCM,data:kEetnw==,iv:70I1DOruChv+h3327Ze0cqSrXkJuVtPr9P2pmiKYAIU=,tag:zb1rRNxHT6wBHoyy84ZEfA==,type:str]
  DB_TYPE: ENC[AES256_GCM,data:j8XozFv6IGo=,iv:qlVEmNcHieUsyAtX3zzVc0aWEKoCDpTQ676Ue0LKRtg=,tag:M1fYsHhEUkpssFri2B6zug==,type:str]
  DB_DSN: ENC[AES256_GCM,data:PeovEz8WLS/dfPeyOxnH86GiKXygRcwbH77YkgzSXhQ+A/lKZU/G7HAcHyaXPz3IQWqS8epJm2gyq5wovw==,iv:G1jvokZ/lmI7tryxydmBsopSaPSV86GJPLC0SVspqls=,tag:LhFgCv1D1++XWg1HLmR6JA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:HA4LuXK+q/9HeoNMWbZHh8N69WJ+ilxnpDTf/J13yrJosqP0cTuF8vxCzu0=,iv:+hXXv16BrUvAGRpN/mc7XWuHCnK9HEKB12dAeSG0NOk=,tag:NZrZyJyD8E+4DUGDyzwZPg==,type:str]
  KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:aT2MayR2zlJvOrKC/bJoFyLhjnampR8hau/msL5QckOyUjAv54dlfQjARjo=,iv:lal8wuX1OHTzt6n0hTgryLb8iewPmF8/SD2HwRZqAIE=,tag:Wul+OKx+CvlGs0AmGbijgQ==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcHJReHBJNndkWThGczFv
        QkQwdnNHUng4a2VJOUFHY0t3cWFMLzVISWo4CkZyeWgzOWFzZWp3SWRvbjZQZ1pX
        RUxPS3BmdTV1NitMYWgwZmtCL1RLNU0KLS0tIFNWanF4SEl5Z242UXVpK2wwSGU5
        N2V0UWhFTWxKY1FLYkFWdlUrcnJRaHcKtgXTOcH+nK9kBR0D5Ofix+OOCTRcwtSy
        ioPmMwYY4Y7XPlCvPU3YCk9cWcLOtJX5kVs+lKg30Sd1O+uOv3Q0vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T11:15:55Z"
  mac: ENC[AES256_GCM,data:izJa5J8negj4KdjUWtNnnMBoQWfOSw1yqzJHNakNFw0fRLc+H8kxXQvGzvUV2FdwdFafIxoHFL2veuZxhZ4MLA41+tGGsWR7/Dd09h9lajaLrXrG2oOXpPPxjwEiAsESnG6mxvpalnMK3NZURnMgkXZhAMI2we6yLYURs39Nkg0=,iv:2a1gw6Mp5BZ6V9SdMY+KPEB4txKX7XN+slpuzmyjsHw=,tag:gDEujLS1zAx0eTtGQlMboA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
