# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: kite-kite-secret
stringData:
  KITE_USERNAME: ENC[AES256_GCM,data:IP9tIQ==,iv:vUJ+4XQZpHPjhGmrUaLoVTCD7ujfClj6kApUQ6RaiyY=,tag:6SmGP+qWADEQJMRzjQ76lA==,type:str]
  KITE_PASSWORD: ENC[AES256_GCM,data:GYdZHw==,iv:NN1ljn1yM5J9C95n2kZGR2lssmaCE8BJpdIvN7QIcOg=,tag:tje2xOA36VC8VzALgPKktw==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:fTh/+ugDq6gJTSc1w+foyVfaaLFw9OUyZiAgWXp6qTrEub7nEva62P2QaWY=,iv:Q70jOtecwNNhMbDQzewq+vvtvvHjoBZ+omRQJtIEdF0=,tag:A3YsjUDpnDecWfz5sVe79w==,type:str]
  KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:UXk2ZpKby0SNOC3xdbGKglRZUnlgpDa/Lz/chgTPsqx2f/lbeQ4lBJUrD8I=,iv:yNWU4jgcuWcztPtjEsliqFZe3v1xzxvDrwRgb8f2OcA=,tag:FF4N0ZOrkOzYd5G26tHK0A==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWkErQXRnQVhCbENJdWtt
        NkdGRUhXZ3NRd0x2Tm1SWCtoQ1NTNFllWTFRCkdvMnIwZmsxckFLVWVJR2dDbmxB
        a0Q4NUZTdWdoV1QxMjlmRkFYdmhNb2cKLS0tIFRVSUtQK1NsZTFiYllHMUFUc1Rv
        UFhMVUg0ekxJWSt4MnQ3VkNjSnlVMjgKElznkSB0KIE6V49YmCpF9wzThPKnm78u
        qtGibnrwUPFwAAyiWM+ve/dOvAkRPNjfZllSH+qCmGN83jtzY312QQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T15:17:19Z"
  mac: ENC[AES256_GCM,data:JjZYNtVfFFHpit3B1ATu6nQ4DtUfkO1vAq8Smq/C6lQL12z3KJQpeCJaYOEBqhkfMply+M/2TKBMe67NgQTvt84mtZeoz6I7v0C0/QrR5Pdijsi2R8ndInZB89PlEfIVI4Ew24XVCNPn4bX66LDAy+YhSPRhPXyhL+KXh0KZAD8=,iv:6DhZipmZWzhcVVfIPkxwnzx8gHf3K8Yeuftr9d93rCI=,tag:ldd6zU8FWqIWV+UYoR8+Ew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
