---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: kite-helm-values
    files:
      - ./values.yaml
secretGenerator:
  - name: kite-helm-secret-values
    files:
      - values.yaml=./values.yaml.encrypted
configurations:
  - ./kustomizeconfig.yaml
