# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-r2-credentials
stringData:
  accessKeyId: ENC[AES256_GCM,data:hTLJbG7sDmInkEsZIykjeKAarJuASoR1jVeTRjPQXhQ=,iv:LG3GRwmiQ4WeVNosI1SvlLGkgLa7kyOND1K3NwkI6BU=,tag:1I8Bd0KWpE5ePJOa5RTKUQ==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:HBMSU0CBHvSZuR1y/Y/jpFgwqAZXkGU/kGB+PvB8Io57yCpgatPxkYbubrAToIdRwylaqfgPbBnYAj143QRoFQ==,iv:2HeW5rCCKq/nGBFXx4QZ+Rg0xVkUiMNVh7XPfrUGqqM=,tag:8mwnxQWsUyeybx2AEqbDJw==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUDVaWHkwLzRGWGRCV2Jn
        SzdaSlR2aUdCZlcxWTBmeU9VV3NiRE1QeW1BCkdVZjk2TFRSUnZVQ3RNb2xkR2tp
        MnFpTUo2R296MFRiNDdEZ2NYS2IzVEEKLS0tIDdsK3FEakRPZ2tsNjQwYlJnNFg1
        K0p1MUIybDRtdENIRmpkT1R3MXhkMHcK8se6eYtfH8DN8dc6Ks4CtgeWXSsY9KcO
        t7JMsoqK/foROJriBj8mGRRcQmDM6RAMlT+oIQnX/utFbFbx4UxgJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T14:43:07Z"
  mac: ENC[AES256_GCM,data:u1IVhhqDZXKn4sYJi0t2cz/97+z2EysbOpB0ktWLBAeHWAe9priqt/dRipARrvKQ/XNjO9QZv0fINIswQghXzS4PZCwjdpC/l8ZlW0yUiqPWyfBEv7su+qgIpl4dV5zc3kHGA76yympxsIvU5CQ9UperS30P9RfVeHoGF5iY87w=,iv:sHbzGxa/PXa4GK8WNyBr1eptlWZd7jIq6qsm11WSuws=,tag:3t/D3R6e/dw7J2/EjRs06w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
