# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-r2-credentials
stringData:
  accessKeyId: 08ac1286396f3e3bb9474cf760251341
  secretAccessKey: beb302e65de281715daf672e52b5126414c13c8086fcede892ef5188cd168fdf
