# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-cloudflare
stringData:
  api-token: ENC[AES256_GCM,data:QIoe1idxGaD8doqvXfmVlfS3Vb0yR9l7XZE1gtRDmz/GZl1uhYdAqw==,iv:bBsGCz/SI/+G0SI0x/e8X9g5+6RZRcEMaYW+JPL29r4=,tag:6jmss7PkMm7RbTsQbJzvEA==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUWdBQ2l0cHNhVkZTcW9R
        MUJXTWNVVTdINXJmclZQdlRIQkR1T3BrNzNBCjVUa3JJOVRjUCt0NVFBVVVCbUVr
        elNXOElKODhuYTdDdkFqMnBSUUFpc28KLS0tIDN3bUZLNUlNVlFxNjVGcGh5OUpC
        SGhJT2RFWXUyN0ExeDJxUGlRY1RFNkUKE3W/fp+mwBhfT4+9YJqzt8gJOkQ/YFe2
        6BTAp/re/xH4or/kbZATdtObXOrbiJ7bot3NTjeYRto7kba/7MpeQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T12:23:34Z"
  mac: ENC[AES256_GCM,data:qqnUoxyqjIhuzw9gUracZgA2TOrthMu5k9pGQaTZ1eKBPGM1QUs92U2MR+03TrambaSU6lqcCv40rQlda1E7D6EMqXjyMJtXlzrKbIl4/gRYz+Hmi5dy7NCwZWI8imxit0tphZJqg2+c6dKtSjNiJQDaigS6VMePGX/SnRIF324=,iv:gZiqYVf9x66p7AIYwYxFJaR6YP+NrX4o1dld40+deY8=,tag:pcLh9WlCHzg6JJteKZpa/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
