---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cert-manager/
  - ./cloudflare.secret.sops.yaml
  - ./local-ca.secret.sops.yaml
  - ./local.certificate.yaml
  - ./local.clusterissuer.yaml
  - ./public-prod.clusterissuer.yaml
  - ./public-stag.clusterissuer.yaml
