# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-auth
stringData:
  username: ENC[AES256_GCM,data:4eKW8SXV6zE=,iv:W3U0x/uEuCszCs4yzYuzJuVWc8w9culHitRf/D3BT10=,tag:mD/N56JVlMCp8Z68UKmTsQ==,type:str]
  password: ENC[AES256_GCM,data:unm1MYoXxPQ=,iv:mxp25D52Iwh2rd8FkrgMVGE5pMll/4TDjXiMFNtF/pk=,tag:lNNhJu0L3WCkhyp+3AtUsA==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWk16NWRleDZtdFErWDdq
        cTJBdXVvSHdrSzhHeEV4WCs5L1liczVVSVFJClJheDNMVjIwWjcxTVBqQWNyNEJL
        cm9KMTZjamdGM1NMRGYzY2lzT21BN0kKLS0tIFpQZm9uWmJuKzlIU0ZZRnZhU0lW
        Z3NzS2FXUVQ4Slp6U2ttbitwY2U3ZU0KkQ/FSa+5hFtGwt5PUDM8mUOPpJjmLau3
        iLdCm2VxeSYETlEVf1EHLZ6oUDmHywRlQrAQs220awu4+SR0PEiT1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T16:52:01Z"
  mac: ENC[AES256_GCM,data:ogkNn0WUvNTWtEZPoQLd4I7aKCJs5o2fmbTKQ5SBOzJTgA+EtY9ySFXLldNgorFKmmzEiQpwqmWnGtxck5SBRagOLzAbFW2mAbvsjLnt2XQj1UiQtrM0xTnCmCCujpr6TWCPNSQT8xj+Qk4mefr7b6CQ8DDTFq1TxF3KBV2uBjg=,iv:pHWn7JG8ykb+1jnxGzg3gonaVgQc/JL/tXdnn3t5W9c=,tag:us/Vr5y6bqfv69syuj0S6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
