---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
namePrefix: cnpg-
labels:
  - pairs:
      app.kubernetes.io/name: cnpg
    includeSelectors: true
resources:
  - ./keycloak-auth.secret.sops.yaml
  - ./keycloak.cluster.yaml
  - ./objectstore.yaml
  - ./r2-credential.secret.sops.yaml
  - ./keycloak.scheduledbackup.yaml
  - ./tlsroute.yaml
configurations:
  - ./kustomizeconfig.yaml
