# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: r2-credentials
stringData:
  accessKeyId: ENC[AES256_GCM,data:z8Igvb8AwKPw1bYlPsTuY43vCyMu/XLPXBCHz6OoBFs=,iv:MHXoIaP+QDFTSUa9qz2rgVWVofJAYqTB1gCxZcLp3Bo=,tag:DzbTo+NVNmZk6YZklWVF7g==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:N7bpezoLOUjhRXdAha5AqZNeK8hoSbADepRGC8wS/XiNq/0svBdiQFmm7jCqZART39UKgNnfKH+2cTgA7VUVFQ==,iv:RGIAL7Vva4il62ejMnKjEYn3QJzMTN2ImSmSnmAyaoA=,tag:rY6oALsfJmX2NYt2F6ZPbw==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYW91NVBJdjhpZy84aFJB
        YXV5SzdxUUVjak0zOEg3UXdBRmgzYWNqNzMwCnh5ZWd0MU4rZmdzd2k3cWk2Um1T
        eWhZRWgvWFhqOXhBZms1K3NER21sSDQKLS0tIGRBbnczZmx5WVlDZHhIVGd3czF2
        eWd5bVNqWEN1SUN4WUZLaGczdGR0ZncKdzXBEn+X9GXkfPowVv8qDxYTnwjdILY9
        XyEDgCt7CV9wH5TgDtdWTQxG9vQNRVw5m9PCHahuq2rgOXp7zElpqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T16:49:36Z"
  mac: ENC[AES256_GCM,data:dsDhp1HnLHFxyEo1DKqKUu+UnLgPSFO6MHfm3TTuYgVsuemvV6w5Vl5f49piZ9Khy2hHYcdcoegmfzD898FZv2S3PoXsn2mWB7+O95KILfa1HFh5rO52topC+zi2N/OWqaYLNz0+rzpgEpwwFWSVpGEHSnqceuAzLFPqLN3+rGs=,iv:v11ozQqkfrb+BHDVhLOEpVeWtR/VYftzVpLBbwYay7U=,tag:1HsCt4H9SuKXe6fqOkKx0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
