---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: authentik-traefik-blueprint
    files:
      - ./traefik-blueprint.yaml
    options:
      disableNameSuffixHash: true
