---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager.yaml
  - ./cnpg-system.yaml
  - ./gateway.yaml
  - ./grafana-operator.yaml
  - ./istio-system.yaml
  - ./monitoring.yaml
  - ./reloader.yaml

  # External usage: my projects,...
  # Maybe disabled when I don't need them
  # - ./atlas-operator.yaml
  # - ./elastic-system.yaml
  # - ./valkey-operator.yaml
  - ./minio-operator.yaml
  - ./redis-operator.yaml
