---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: cnpg
    includeSelectors: true
resources:
  - ./cluster.yaml
  # - ./objectstore.yaml
  - ./postgres-auth.secret.sops.yaml
  # - ./r2-credential.secret.sops.yaml
  # - ./scheduledbackup.yaml
  # - ./tlsroute.yaml
