# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-postgres-auth
stringData:
  username: ENC[AES256_GCM,data:k2jwSAH3rg==,iv:Nff8MBdkgpEIeblKZjKPXRd8+M1aM/Mu1CgOiCyBbIQ=,tag:ntX3F6nHUGJfTsPcFSQRqQ==,type:str]
  password: ENC[AES256_GCM,data:iEUvYQqqHQ==,iv:ovEpOyKS3j1/hirELR2CeTPGrrfoyUZcuUipkB1FTUw=,tag:7WJC/TlMjVR3LR6Z4mdMJw==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMkR5RlNnSlAxbmMwTGx6
        YUpBVWJOalo4YThnOTI1K2NCUUcrV3ZEd1hrCmxuVUtaby91aTN5bVhrN0lwQmZX
        V1VBcExsTDd4N0g3d3lsc2Q5VjFZTVUKLS0tIDdieXkvV1ByY2xUUTQvdkt3R3dt
        RXdIV2grbWIrNW9FT0RDTkJnM1kwVE0KiUKk4l9BRyBFkZhpgTbsUakpNC5zygRH
        Cji3bFjlPEGgATi8XSZfTs7OHczXE6Gaac54LFxu87HUyGHkfKzKhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T01:14:59Z"
  mac: ENC[AES256_GCM,data:sy0/6hQd7sYu14sxxB4r+WGKVyJ7Y/ts2fbbOhrQ6PEzsQVJUVqO/miS2G8rhTO3Mn825W1m3twWfK/8vuRmdahD2A3IwVktXwqLCxc3nE4xIAr1csuzQWIx3ajU1o9zVBjbPywdnUUriKzJ7yxNrkZh8HSJof9HnOI7Z1ub5ao=,iv:0BxS7RqO7cpkGYw+8DnvNwstiuZtRBD8iuLJKg5I+j0=,tag:u9hmg2nLTXZbWwA1l7ctwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
