# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-postgres-auth
stringData:
  username: ENC[AES256_GCM,data:UAvZe09YSg==,iv:N8uDjLg6idAMCoSIQL+ClZGb8nQPvZCFu+vThRgAgCs=,tag:mIQ97hnoA078p8XofTPhxg==,type:str]
  password: ENC[AES256_GCM,data:JBjM8/ygxQ==,iv:/03R9IvC7JTTgcrZqWUFbM3zzmk+OpdsiV1ajbNFmyY=,tag:brEZDK1rUIvlfJ0ZznpxFA==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMamFydzdFRk9pN21ENnN3
        MTdKaHJ2Rlh6UWFXVDdJWTB5eWkvUTIzMzNrCkFLQlF5U0hWSm5FRGQ1Z0NtWkxT
        M2doa3dvaTEzWUJnaHhzZ3hjSXBTek0KLS0tIGZ1WFFYbElTR3RheVVNS2VpR29V
        d2hMN29JZHdmYzN1dlVHYXVyZkNSTmsKI9JOBodkWhrMzLjXJMMZmKs9dujvID5L
        CNN/v3eQVWa/WnFRkvtcbVjg0CD+BOgEQJNb91A4VyX6T1Q6ruedNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T01:08:50Z"
  mac: ENC[AES256_GCM,data:O+BX23CBuiKqp1k4iWLT6Bi/E7/rxYUskd6rbELsMXBAYnk39RYH5B+0QE07B18kNAbruSqhVmDOETD+6Okr15CywUjoQzxsjRWdNuVAh2LGz33GXJuVFA9Qo1kdcwDvmeKkZy1Bet3DFGR2lQ4qcEp6WmtqWGMFvLmxI86F+XA=,iv:jtVx9VGtJbxTDjmX4F4G74W0em2kk4xrdJsCqANwdEE=,tag:z2wZ1Utc7JQUeyrWuG8PWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
