---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local
spec:
  issuerRef:
    name: local
    kind: ClusterIssuer
  secretName: local-tls
  commonName: "${LOCAL_DOMAIN}"
  dnsNames:
    - ${LOCAL_DOMAIN}
    - alertmanager.${LOCAL_DOMAIN}
    - alloy.${LOCAL_DOMAIN}
    - authentik.${LOCAL_DOMAIN}
    - cloudbeaver.${LOCAL_DOMAIN}
    - filebrowser.${LOCAL_DOMAIN}
    - glance.${LOCAL_DOMAIN}
    - grafana.${LOCAL_DOMAIN}
    - kite.${LOCAL_DOMAIN}
    - metube.${LOCAL_DOMAIN}
    - prometheus.${LOCAL_DOMAIN}
