---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanager-telegram.secret.sops.yaml
  - ./alertmanager.grafanadatasource.yaml
  - ./grafana/
  - ./helm-release.yaml
  - ./prometheus.grafanadatasource.yaml
configMapGenerator:
  - name: kube-prometheus-stack-helm-values
    files:
      - ./values.yaml
configurations:
  - ./kustomizeconfig.yaml
