---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: dbgate
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: dbgate
  to:
    - group: ""
      kind: Service
      name: ak-outpost-authentik-embedded-outpost
