---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./cloudbeaver.referencegrant.yaml
  # - ./redis-commander.referencegrant.yaml
  - ./dbgate.referencegrant.yaml
  - ./monitoring.referencegrant.yaml
  - ./traefik.referencegrant.yaml
