---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cloudbeaver-https
spec:
  parentRefs:
    - &gateway
      name: default
      namespace: traefik
      sectionName: http-wildcard
    - <<: *gateway
      sectionName: http-wildcard-local
  hostnames:
    - cloudbeaver.${PUBLIC_DOMAIN}
    - cloudbeaver.${LOCAL_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: traefik-auth
      backendRefs:
        - name: cloudbeaver-cloudbeaver
          port: 8978
