---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: cloudbeaver
    includeSelectors: true
resources:
  - ../../../base/cloudbeaver/cloudbeaver/
  - ./http.httproute.yaml
  - ./https.httproute.yaml
