# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-kite-auth
stringData:
  username: ENC[AES256_GCM,data:82RwDw==,iv:XLnGgk5YS0xZUciM/3W77iL73RqleZ2JV6S80086tW4=,tag:X1cB3CWRycv5m0Tl2Qhytg==,type:str]
  password: ENC[AES256_GCM,data:mJNfxA==,iv:ZwvoTK42Hpimmmv+FKCzzGf32tB9tOT8Kta67YhPmCw=,tag:VLI/6tswp+YhTQENJjZsAw==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cTVhY3l1cVVMdVRHK1pM
        M3Fhb1duSHhOcWtTQkRNRTNqRGk0b29jaVY4CnZ3YmFYZ3pVZmxRSWpta3dLS241
        WlJMUzEvNm02MjZ3bFFJaXFLOUNmU3MKLS0tIFkxSmo0QXBEVCszVzl4cU5HN1NN
        T0EyZTMwSmFnY3h3QVJoOHJNTjVRR2MKG5OKVz70Nsr7waSfjL6idsOnSk4Kag9R
        IYzvbr2905x3rHjQnFno4ECrrZpzg3MeeMpILWsTEcZxXSlzvHhm5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T03:07:59Z"
  mac: ENC[AES256_GCM,data:p7lzeOiuWLtBRpwnDqc/ZAuIjWLY0BVoIXyrwUTAY/AAkm3Oh+QWsvokPzjuKTSqXHYbRL69yXCp+HHWaimREqV0oBn2dLPwamcBmx4m6Xoc1Qg55NmbwrzcjvzIOB8LUMpahvTucaPuV6JmNDIdAsGkE6zQhvyiGsLppxSs2mQ=,iv:tlDWiTg+w/XoY5hjDceyVinKRGOm53N2lRt2OtO845c=,tag:a5GN6NZnevdDoonlrHwjZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
