# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-r2-credentials
stringData:
  accessKeyId: ENC[AES256_GCM,data:Vt7pbNWE64wo4L0+n4CnYOSZa0aWsqLp/INUOqXPxYY=,iv:iMHZ8VSnefiw35cgwmdtJ1pJXxYlHT5rEIBiKKmvP1I=,tag:bVsFMnemROGI35i1zdL+5A==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:6rdJcFxXLJ4m+FM5DFEFQD9XJ2GHMKwP9E3JvXTVX1Rcri8yJITiFsNhkb8/sNnMx1/luRcIWRegXGU37uSUxw==,iv:VZ9LhVzq5jkpswZQ1jQt1yMGiAgQo2IMsy1gkqOE1xQ=,tag:0KGJpwSVQ7eI4XmYFam3Cg==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcGNvQVJpV3FpUEhabTFp
        Y2dtTHcyQlpWTlRCNGViRkhTL3FuUFVDVEFvCnZnYngyTERKWTRuUnl0ZHBlOWtx
        bFlxdFFIZGlmNS9FajJKcXgvbEpPNzAKLS0tIHo0cGl2WkVQNVloKzlDNU5PVjBI
        K2JaQU92aVN3SVBqU1VVMDdtN2VFeDAKKYTwnhf8wY1C/VfZG9/+PaMb4fDis3zs
        SY0qFc0SokG6olFHMIl/e7pNmEm8QKf1xLxBGU7jmzBU62sOnNEtkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T03:13:32Z"
  mac: ENC[AES256_GCM,data:GeBKcqAcl/ROREZQ9ewZxJ7q2AhUzWpyiY/S+Ehvv5fdrksax/f7UfR+XtAOdH/jRaN6oEtMLxKkqM3YFjKPZ+IzrQZSbkn/l5ISkYLMfO2NBjbyt+VgkY9hno8zU68B+I0Jxb9FGpjVSiWiOCzwdGTCddhLBa7KdRGV/XjEA24=,iv:YEZkZx0rBq3Z5D4bKYQLaWVBA28AW6Vi/VY6LiHlwxI=,tag:NEvCsH0l9QS9mtTUuqrRaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
