---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-cloudflared
  annotations:
    reloader.stakater.com/auto: "true"
    glance/icon: si:cloudflare
spec:
  template:
    metadata:
      name: cloudflared-cloudflared
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ping_group_range
            value: "65532 65532"
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:1759-f9c2bd51ae24
          ports:
            - containerPort: 8080
          command:
            - cloudflared
            - tunnel
            - run
          env:
            - name: TUNNEL_METRICS
              value: 0.0.0.0:8080
            - name: NO_AUTOUPDATE
              value: "true"
          envFrom:
            - secretRef:
                name: cloudflared-env
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
  selector: {}
