---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service.json
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-cloudflared
spec:
  ports:
    - port: 8080
      name: metrics
