---
authentik:
  bootstrap_token: ${AUTHENTIK_BOOTSTRAP_TOKEN}
  bootstrap_password: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
  secret_key: ${AUTHENTIK_SECRET_KEY}
  error_reporting:
    enabled: false
  postgresql:
    host: cnpg-authentik-rw
    name: authentik
    user: authentik
    password: ${AUTHENTIK_DB_PASSWORD}
