---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name metube
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      name: *name
    spec:
      containers:
        - name: *name
          image: ghcr.io/alexta69/metube:2025.12.14
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: &downloads downloads
              mountPath: /downloads/
          envFrom:
            - secretRef:
                name: env
      volumes:
        - name: *downloads
          persistentVolumeClaim:
            claimName: *downloads
  selector: {}
