---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: public-prod
spec:
  acme:
    email: kevinnitro@duck.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: public-certificate-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: api-token
        selector:
          dnsZones:
            - ${PUBLIC_DOMAIN}
