---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./flux-system/
  - ./ks/app.yaml
  - ./ks/infrastructure-config.yaml
  - ./ks/infrastructure-controller.yaml
  - ./ks/monitoring.yaml
components:
  - ../../component/setting/
